apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: logistica
type: Opaque
stringData:
  password: REPLACE_WITH_KUBERNETES_SECRET
---
apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: logistica
type: Opaque
stringData:
  jwt-secret: REPLACE_WITH_KUBERNETES_SECRET
